// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm5YRvwdIyjWFL4tUUp1Hah3yCT5zXahY',
    appId: '1:817765454716:web:2e8a81efe1de7faea2caf9',
    messagingSenderId: '817765454716',
    projectId: 'atf-marvel-heroes',
    authDomain: 'atf-marvel-heroes.firebaseapp.com',
    storageBucket: 'atf-marvel-heroes.appspot.com',
    measurementId: 'G-JR0XWKFZ2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5soO02dtBQ4oCcdafzfqEfVJjrRuHgBY',
    appId: '1:817765454716:android:9474a3025d7432dba2caf9',
    messagingSenderId: '817765454716',
    projectId: 'atf-marvel-heroes',
    storageBucket: 'atf-marvel-heroes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqs1bKed6DiSzycndJoD9x38BXHeGSKrw',
    appId: '1:817765454716:ios:4f994b2b22aa1c9fa2caf9',
    messagingSenderId: '817765454716',
    projectId: 'atf-marvel-heroes',
    storageBucket: 'atf-marvel-heroes.appspot.com',
    iosClientId: '817765454716-ginuaqjkuvvqrhd9l0qj7rcpjo20pr0h.apps.googleusercontent.com',
    iosBundleId: 'com.atf-marvel-heroes',
  );
}
